config/routes.rb
Cyti2::Application.routes.draw do
  resources :sessions
  resources :users
  resources :events

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get "welcome/index"

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  # Use HTTParty to conenct to Parse.com
  # include HTTParty
  # format :json
  # headers['X-Parse-Application-Id'] = ENV["PARSE_APP_ID"]
  # headers['X-Parse-REST-API-Key'] = ENV["PARSE_KEY"]
  # headers["Content-Type"] = "application/json"

  Parse.init :application_id => ENV["PARSE_APP_ID"], :api_key => ENV["PARSE_KEY"]

  # Switched from this method to 'ordered'.  Can probably delete this.
  def self.all
    event = Parse::Query.new("Event").exists("objectId").get
  end

  # def self.by_user(user)
  #   event = Parse::Query.new("Event").eq("createdByNew", user).get
  # end

  def self.ordered(direction, sort_type, user)
    event = Parse::Query.new("Event").eq("createdByNew", user).tap do |q|
      if direction == "descending"
        q.order_by = "-" + sort_type
      else
        q.order_by = sort_type
      end
    end.get
  end

  # def self.search(keyword)
  #   event = Parse::Query.new("Event").eq("title", keyword).get
  # end

  # Returns an array
  def self.find_by_objectId(objectId)
    event = Parse::Query.new("Event").eq("objectId", objectId).get
  end

  def self.update(event_params)
    event = Parse::Query.new("Event").eq("objectId", event_params[:objectId]).get.first
    event["address"] = event_params[:address]
    event["endDate"] = Parse::Date.new(event_params[:endDate])
    event["imageThumbUrl"] = event_params[:imageThumbUrl]
    event["moreInfo"] = event_params[:moreInfo]
    event["shortDescription"] = event_params[:shortDescription]
    event["title"] = event_params[:title]
    event.save
  end

    def self.create(event_params)
    event = Parse::Object.new("Event")
    event["address"] = event_params[:address]
    event["endDate"] = Parse::Date.new(event_params[:endDate])
    event["imageThumbUrl"] = event_params[:imageThumbUrl]
    event["moreInfo"] = event_params[:moreInfo]
    event["shortDescription"] = event_params[:shortDescription]
    event["title"] = event_params[:title]
    event.save
  end

  def self.destroy(objectId)
    event = Parse::Query.new("Event").eq("objectId", objectId).get.first
    event.parse_delete
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	Parse.init :application_id => ENV["PARSE_APP_ID"], :api_key => ENV["PARSE_KEY"]

	def self.all
		user = Parse::Query.new("_User").exists("objectId").get
	end

	def self.create(user_params)
		user = Parse::User.new({
			:username => user_params["username"],
			:email => user_params["email"],
			:password => user_params["password"]
			})
		user.save
	end

	def self.find_by_objectId(objectId)
		user = Parse::Query.new("_User").eq("objectId", objectId).get
	end

	def self.login(session_params)
		user = Parse::User.authenticate(session_params[:username], session_params[:password])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def authorize
    redirect_to login_url, alert: "Not logged in" if session[:sessionToken].nil?
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]
  before_filter :authorize

  # GET /events
  # GET /events.json
  def index
    @events = Event.ordered(params[:direction], params[:sort], session[:objectId]).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.create(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event = Event.update(event_params)

    respond_to do |format|
      if @event
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit', notice: 'Event not updated.' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    # Using 'id' instead of 'objectId' here since Rails sets objectId passed in params to 'id'
    @event = Event.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # GET from Parse by objectId
    def set_event
      # Using 'id' instead of 'objectId' here since Rails sets objectId passed in params to 'id'
      @event = Event.find_by_objectId(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.permit(:objectId, :id, :address, :endDate, :imageThumbUrl, :moreInfo, :shortDescription, :title, :utf8, :_method, :authenticity_token, :commit)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	@user = User.login(session_params)
  	if @user
  		session[:sessionToken] = @user["sessionToken"]
      session[:objectId] = @user["objectId"]
  		redirect_to root_url, notice: "Logged in"
  	else
  		flash.now.alert = "Email or password is invalid"
  		render "new"
  	end
  end

  def destroy
  	session[:sessionToken] = nil
  	reset_session
  	redirect_to root_url, notice: "Logged out."
  end

  private

  def session_params
      params.permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.create(user_params)

    respond_to do |format|
      if @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_objectId(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:username, :password, :emailVerified, :email, :zipcode)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authorize

  def index
    @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == params[:sort] && params[:direction] == "ascending" ? "descending" : "ascending"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # def self.get_user(sessionToken)
  #   user = HTTParty.get('https://api.parse.com/1/users/me')
  # end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_tag(event_path, method: 'put', :class => "form-horizontal")  do %>
  <fieldset>
    <% @event.each do |event| %>
      <%= hidden_field_tag(:objectId, event["objectId"]) %>

      <div class="form-group">
        <%= label_tag(:title, "Title:", :class => "col-lg-2 control-label") %>
        <div class="col-lg-10">
          <%= text_field_tag(:title, event["title"], :class => "form-control") %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag(:address, "Address:", :class => "col-lg-2 control-label") %>
        <div class="col-lg-10">
          <%= text_field_tag(:address, event["address"], :class => "form-control") %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag(:endDate, "End Date:", :class => "col-lg-2 control-label") %>
        <div class="col-lg-10">
          <%= text_field_tag(:endDate, event["endDate"] ? event["endDate"].value.to_date : nil, :class => "form-control") %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag(:moreInfo, "More Info:", :class => "col-lg-2 control-label") %>
        <div class="col-lg-10">
          <%= text_field_tag(:moreInfo, event["moreInfo"], :class => "form-control") %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag(:shortDescription, "Short Description:", :class => "col-lg-2 control-label") %>
        <div class="col-lg-10">
          <%= text_area_tag(:shortDescription, event["shortDescription"], :class => "form-control") %>
        </div>
      </div>
    <% end %>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= link_to events_path, class: 'btn btn-default cancel lineup',  :confirm => 'Cancel without saving?' do %>
          Cancel
          <% end %>
          <%= submit_tag("Submit", :class => "btn btn-primary") %>
        </div>
      </div>
  </fieldset>
<% end %>

app/views/events/edit.html.erb
<h1>
  <% @event.each do |event| %>
    <%= event['title'] %>
  <% end %>
</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <h1>Events</h1>
  </div>
  <div class="col-md-9">
    <%= button_to 'New Event', new_event_path, method: 'get', class: "btn btn-primary btn-sm movedown25 float-right" %>
  </div>
</div>
<%# form_tag events_path, :method => 'get' do %>
  <!-- <p>
    <%# text_field_tag :search, params[:search] %>
    <%# submit_tag "Search", :name => nil %>
  </p> -->
<%# end %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= sortable "Title" %></th>
      <th><%= sortable "Address" %></th>
      <th><%= sortable "endDate", "End Date" %></th>
      <th><%= sortable "shortDescription", "Short Description" %></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event['title'] %></td>
        <td><%= event['address']%></td>
        <td><%= event['endDate'] ? event['endDate'].value.to_date : nil %></td>
        <td><%= event['shortDescription'] %></td>
        <td><%= link_to edit_event_path(event['objectId']) do %>
          <%= fa_icon "edit", class: "edit-icon" %>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @events %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= form_tag(events_path, method: 'post', :class => "form-horizontal") do %>
  <fieldset>
    <div class="form-group">
      <%= label_tag(:title, "Title:", :class => "col-lg-2 control-label") %>
      <div class="col-lg-10">
        <%= text_field_tag(:title, nil, :placeholder => 'Title', :class => "form-control") %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag(:address, "Address:", :class => "col-lg-2 control-label") %>
      <div class="col-lg-10">
        <%= text_field_tag(:address, nil, :placeholder => 'Address', :class => "form-control") %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag(:endDate, "End Date:", :class => "col-lg-2 control-label") %>
      <div class="col-lg-10">
        <%= text_field_tag(:endDate, nil, :placeholder => 'End Date', :class => "form-control") %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag(:moreInfo, "More Info:", :class => "col-lg-2 control-label") %>
      <div class="col-lg-10">
        <%= text_field_tag(:moreInfo, nil, :placeholder => 'More Info', :class => "form-control") %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag(:shortDescription, "Short Description:", :class => "col-lg-2 control-label") %>
      <div class="col-lg-10">
        <%= text_area_tag(:shortDescription, nil, :placeholder => 'Short Description', :class => "form-control") %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= submit_tag("Submit", :class => "btn btn-primary") %>
      </div>
    </div>

  </fieldset>
<% end %>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cyti2</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="../"><%= image_tag('logos/cyti_logo_long_120_trans_bg.png', :class => 'moveup13') %></a>
          <button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar-main" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if session[:sessionToken] %>
              Hello, <%# link_to (current_user['name'] || current_user['email']), welcome_index_path %>!
              <li><%= link_to "Log Out", logout_path, method: 'delete' %></li>
            <% else %>
              <li><%= link_to "Sign Up", signup_path %></li>
              <li><%= link_to "Log In", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Dashboard", root_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "Issues", root_path %></li>
        <li><%= link_to "News", root_path %></li>
      </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%=flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
      </div>
    <% end %>
	    <%= yield %>

    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :emailVerified %><br>
    <%= f.check_box :emailVerified %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Emailverified</th>
      <th>Email</th>
      <th>Zipcode</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user['username'] %></td>
        <td><%= user['password'] %></td>
        <td><%= user['emailVerfied'] %></td>
        <td><%= user['email'] %></td>
        <td><%= user['zipcode'] %></td>
        <td><%= link_to 'Show', user_path(user['objectId']) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Login', new_session_path %>

app/views/users/new.html.erb
<h1>New user</h1>
	<%= form_tag(users_path, method: 'post') do %>
    <div class="field">
      <%= label_tag(:username, "Username:") %><br>
      <%= text_field_tag(:username) %>
    </div>
    <div class="field">
      <%= label_tag(:email, "Email:") %><br>
      <%= text_field_tag(:email) %>
    </div>
    <div class="field">
      <%= label_tag(:password, "Password:") %><br>
      <%= password_field_tag(:password) %>
    </div>
    <div class="actions">
      <%= submit_tag("Submit") %>
    </div>
  <% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% @user.each do |user| %>

  <p>
    <strong>Username:</strong>
    <%= user['username'] %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user['password'] %>
  </p>

  <p>
    <strong>Emailverified:</strong>
    <%= user['emailverified'] %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user['email'] %>
  </p>

  <p>
    <strong>Zipcode:</strong>
    <%= user['zipcode'] %>
  </p>

<% end %>

<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Dashboard</h1>
<div class="row">
  <div class="col-lg-4">
    <h3>My Events</h3>
    <ul>
      <% @events.each do |event| %>
        <li>
          <%= link_to event['title'], event_path(event['objectId']) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-lg-4">
    <h3>My Issues</h3>
    <ul>
      <% @events.each do |event| %>
        <li>
          <%= link_to event['title'], event_path(event['objectId']) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-lg-4">
    <h3>My News</h3>
    <ul>
      <% @events.each do |event| %>
        <li>
          <%= link_to event['title'], event_path(event['objectId']) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>